

- import_tasks: ubuntu.yml
  when: ansible_distribution == ubuntu

#- name: "{{ container_name }} - stop container"
#  shell: "docker container stop {{ container_name }}"

- name: "{{ container_name }} backup {{ mount_point }}"
  shell: docker run --rm --volumes-from {{ container_name }} -v {{ backup_location }}:/backup ubuntu bash -c 'cd {{ mount_point }} && tar cvf /backup/{{ tar_file }} .'

 