

- name: Debian - Install docker CLI
  apt:
    name: docker
    state: present
  when: ansible_os_family == 'Debian'

- name: Redhat - Install docker CLI
  yum:
    name: docker
    state: present
  when: ansible_os_family == 'RedHat'

- name: OSX - Install docker CLI
  homebrew:
    name: docker
    state: present
  when: ansible_os_family == 'darwin'

- import_tasks: backup.yml
  when: role_action == 'backup'

- import_tasks: restore.yml
  when: role_action == 'restore'

