- name: Make new volume - {{ volume_name }}
  docker_volume:
    name: "{{ volume_name }}"
    state: present
  when: create_volume == true

- name: Stop Container if running - {{ container_name }}
  shell: docker container stop {{ container_name }}
  ignore_errors: true
  when: stop_container == true

- name: restore data from tar
  shell: docker run --rm -v {{ volume_name }}:/recover -v {{ backup_folder }}:/backup ubuntu bash -c 'cd "/recover/{{ recovery_folder }}" && tar xvf /backup/{{ tar_file }}'

